### ISSUE TITLE
maxDate drawing issues

### ISSUE THREAD

**Issue by strooooke** [afollestad/date-picker#5]
*Please consider making a Pull Request if you are capable of doing so.*
I'd love to, but it would take me a while, as I have other obligations for the next few weeks.

**Library Version:**

0.4.2
 
**Affected Device(s):**
 
Google Pixel (1) with Android 9.0
Huawei ALE-21 with Android 6.0
...probably others.
 
**Describe the Bug:**

I'm showing datepickers in a dialog, very similar to the material-dialogs datepicker option; here's the relevant parts:

```kotlin
fun MaterialDialog.datePicker(
        initialDate: LocalDate? = null,
        requireNonFutureDate: Boolean = false,
        onDateSet: ((LocalDate?) -> Unit)? = null,
        allowNoDate: Boolean = false
): MaterialDialog {
    customView(
            R.layout.dialog_datepicker,
            noVerticalPadding = true,
            dialogWrapContent = false
    )

    (initialDate ?: LocalDate.now()).let {
        datetimeDatePicker.setDate(
                it.year,
                it.monthValue - 1, // datepicker uses java calendar constants which are 0-based
                it.dayOfMonth
        )
    }
    if (requireNonFutureDate) {
        datetimeDatePicker.setMaxDate(Calendar.getInstance())
    }

   positiveButton(...)
 
   negativeButton(...)

   return this
}
```

Upon showing the dialog, I see

<img src="https://user-images.githubusercontent.com/856723/60282817-1d303f00-9908-11e9-918a-6df7eac7932e.png" width="250" />

on both phones; I would have expected the "grey tube" to show immediately.

Upon clicking any date, I do see the "grey tube", but something's off with the drawing:

<img src="https://user-images.githubusercontent.com/856723/60282941-62547100-9908-11e9-9a4a-e0b0220765d2.png" width="250" />

on the Huawei, and 

<img src="https://user-images.githubusercontent.com/856723/60324818-17793e80-9986-11e9-8d6a-99c6d4dff0dc.png" width="250" />

on the Pixel.

**Comment by strooooke** [comment]
(Sorry, I had the wrong third screenshot; updated the description now.)

**Comment by afollestad** [comment]
The latest release should help.
