### ISSUE TITLE
If minDate is in the future, initially shown month is confusing

### ISSUE THREAD

**Issue by strooooke** [afollestad/date-picker#9]
If showing the datepicker, with e.g. minDate set a month in the future (in any case, such that the current month is completely in the invalid range), but without pre-selecting a date, the current month is shown, but completely invalid. That doesn't really communicate well to the user what's up.

I'm not sure what exactly I'd like instead - some options I'm seeing:
- allow setting the displayed month independent of the selected date
- automatically display the closest month to `now` that contains valid dates
- decide that this is not a desired feature and that in such a situation, clients should pre-select a date too.

Personally, I'd lean towards that second option and would be happy to implement it (or another one) - do you have preferences or ideas about this?

**Comment by strooooke** [comment]
Yes, nevermind - I see now that this is meant to work as the second option. It doesn't for me, for the same reason that some other stuff does not - when using datepicker in a dialog, in the naive way (inflate a view, call e.g. `setDate` and then maybe later `setMaxDate` and/or `setMinDate`, then show the dialog with this content view (triggering `onAttachedToWindow`)), the order of the method calls is not as expected.

**Comment by afollestad** [comment]
In the sample project, setting the min date in the future successfully makes the initially shown month view in the future as well. I'm unable to reproduce any problems here.
